pool: centos


steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'trivy repo https://github.com/nullx3d/WebGoat'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'trivy image webgoat/webgoat-8.0'