trigger:
- main

pool: default


steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '8'
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled
- task: NexusIqPipelineTask@1
  inputs:
    nexusIqService: 'sonatype'
    applicationId: 'batu'
    stage: 'release'
