trigger:
- master

pool: default

steps:
- task: FortifySCA@7
  inputs:
    applicationType: 'java'
    buildSourceVersion: '11'
    fortifyBuildId: 'webgoatjava'
    fortifyScanType: 'LocalScan'
    runFortifyUpload: true
    fortifyServerName: 'ssc test'
    fortifyApplicationName: 'webgoatjava'
    fortifyApplicationVersion: 'webgoatjava'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $fortify_ssc_api_url = "$(ssc_api)"
      $token = "FortifyToken $(token)"
      $x = 5

      $headers = @{
          "Authorization" = $tokens
          "Content-Type" = "application/json"
          "Accept" = "application/json"
      }
          # Api request get
          $response = Invoke-WebRequest -Uri $fortify_ssc_api_url -Method Get -Headers $headers -UseBasicParsing
              $project_versions_data = $response.Content | ConvertFrom-Json
                if($project_versions_data.count -ge $x){
                Write-Host "Pipeline Broken. Error Status: Exit Code 1"
                Exit 1
                }
                return $project_versions_data.count