pool: centos

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      chmod -R 777  ./
      
      docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -t https://dzone.com -g gen.conf -x OWASP-ZAP-Report.xml -r scan-report.html